version: '3.8'

services:
  orchestrator:
    build:
      context: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - .:/app
      - ~/.cache/chroma:/root/.cache/chroma
    working_dir: /app
    command: uvicorn orchestrator.api:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - ollama

  ollama:
    build:
      context: .
      dockerfile: Dockerfile.ollama
    ports:
      - "11434:11434"
    environment:
      - OLLAMA_HOST=0.0.0.0
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data: